---
version: '3.6'

x-besu-def:
  &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |

      cp "/config/${BESU_CONS_ALGO:-QBFT}genesis.json" /config/genesis.json

      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,${BESU_CONS_ALGO:-QBFT} \
      --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,${BESU_CONS_ALGO:-QBFT} ;





x-splunk-def:
  &splunk-def
  image: splunk/splunk:8.2
  container_name: splunk
  environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_PASSWORD=quickstart
    - SPLUNK_APPS_URL=https://github.com/splunkdlt/splunk-app-quorum/releases/download/1.0.9/splunk-app-quorum-v1.0.9.tgz
  ports:
    - 8000:8000
    - 8088:8088
  healthcheck:
    test: ['CMD', 'curl', '-f', 'http://localhost:8000']
    interval: 5s
    timeout: 5s
    retries: 20
  volumes:
    - ./splunk/splunk.yml:/tmp/defaults/default.yml
    - splunk:/opt/splunk/var

x-otelcollector-def:
  &otelcollector-def
  image: quay.io/signalfx/splunk-otel-collector:0.26.0
  container_name: otelcollector
  depends_on:
    - splunk
  command:
    - --config
    - /etc/otel/config.yaml
  volumes:
    - ./splunk/otel-collector-config.yml:/etc/otel/config.yaml
    - /var/log:/var/log
  environment:
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_ACCESS_TOKEN=disable # You can use this option to send data to Splunk Cloud.
    - SPLUNK_REALM=disable # You can use this option to send data to Splunk Cloud.

x-ethlogger-def:
  &ethlogger-def
  image: ghcr.io/splunkdlt/ethlogger:3.0.1
  container_name: ethlogger
  environment:
    - COLLECT_PEER_INFO=true
    - COLLECT_PENDING_TX=true
    - ETH_RPC_URL=http://rpcnode:8545
    - NETWORK_NAME=quickstart
    - START_AT_BLOCK=latest
    - SPLUNK_HEC_URL=https://splunk:8088
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_EVENTS_INDEX=ledger
    - SPLUNK_METRICS_INDEX=metrics
    - SPLUNK_INTERNAL_INDEX=metrics
    - SPLUNK_HEC_REJECT_INVALID_CERTS=false
    - ABI_DIR=/app/abis
    - DEBUG=ethlogger:platforms,ethlogger:eth
  volumes:
    - ethlogger:/app
    - ./smart_contracts/contracts:/app/abis
  depends_on:
    - splunk
  restart: unless-stopped

x-docker-logging:
  &docker-logging
  logging:
    driver: "splunk"
    options:
      splunk-token: "11111111-1111-1111-1111-1111111111113"
      splunk-url: "https://localhost:8088"
      splunk-index: "logs"
      splunk-insecureskipverify: "true"
      splunk-verify-connection: "false"
      splunk-format: "json"
      tag: "{{.Name}}-{{.ID}}"
      splunk-sourcetype: "docker:logging"
      splunk-source: quorum-quickstart







x-chainlensapi-ref:
  &chainlensapi-def
  image: web3labs/epirus-free-api:latest
  container_name: chainlensapi
  environment:
    - NODE_ENDPOINT=http://rpcnode:8545
    - MONGO_CLIENT_URI=mongodb://chainlensmongodb:27017
    - REINDEX_ENDPOINT=http://chainlensingestion/reindex/
    - MONGO_DB_NAME=epirus
    - MONGO_CREATE_INDICES=true
  depends_on:
    - chainlensmongodb

x-chainlensmongodb-ref:
  &chainlensmongodb-def
  image: mongo:5.0.8
  container_name: chainlensmongodb
  environment:
    - COMPOSE_HTTP_TIMEOUT=900
    - DOCKER_CLIENT_TIMEOUT=900
  entrypoint: mongod --bind_ip "0.0.0.0"

x-chainlensweb-ref:
  &chainlensweb-def
  image: web3labs/epirus-free-web:latest
  container_name: chainlensweb
  environment:
    - API_URL=/api
    - DISPLAY_NETWORK_TAB=disabled
  depends_on:
    - chainlensapi

x-chainlensingestion-ref:
  &chainlensingestion-def
  image: web3labs/epirus-free-ingestion:latest
  container_name: chainlensingestion
  environment:
    - NODE_ENDPOINT=http://rpcnode:8545
    - MONGO_CLIENT_URI=mongodb://chainlensmongodb:27017
    - MONGO_DB_NAME=epirus
  depends_on:
    - chainlensmongodb
    - chainlensweb

x-chainlensnginx-ref:
  &chainlensnginx-def
  image: nginx:latest
  container_name: chainlensnginx
  volumes:
    - ./chainlens/nginx.conf:/etc/nginx/nginx.conf
    - ./chainlens/5xx.html:/www/error_pages/5xx.html
  ports:
    - 8081:80
  depends_on:
    - chainlensapi
    - chainlensweb



x-ethsignerProxy-def:
  &ethsignerProxy-def
  image: consensys/ethsigner:${ETHSIGNER_VERSION:-latest}
  command: [
    "--chain-id=1337",
    "--http-listen-host=0.0.0.0",
    "--downstream-http-port=8545",
    "--downstream-http-host=rpcnode",
    "file-based-signer",
    "-k",
    "/opt/ethsigner/keyfile",
    "-p",
    "/opt/ethsigner/passwordfile"
  ]
  ports:
    - 8545

services:

  validator1:
    << : *besu-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator1,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *besu-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator2,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator2:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *besu-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator3,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator3:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *besu-def
    ports:
      - 21004:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator4,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator4:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *besu-def
    container_name: rpcnode
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=rpcnode,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/rpcnode:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15

  ethsignerProxy:
    << : *ethsignerProxy-def
    volumes:
      - ./config/ethsigner/password:/opt/ethsigner/passwordfile
      - ./config/ethsigner/key:/opt/ethsigner/keyfile
    depends_on:
      - validator1
      - rpcnode
    ports:
      - 18545:8545/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.40



  explorer:
    image: consensys/quorum-explorer:${QUORUM_EXPLORER_VERSION:-latest}
    volumes:
      - ./quorum-explorer/config.json:/app/config.json
      - ./quorum-explorer/env:/app/.env.production
    depends_on:
      - rpcnode
    ports:
      - 25000:25000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.31





  chainlensapi:
    <<: *chainlensapi-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.53

  chainlensmongodb:
    <<: *chainlensmongodb-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.54

  chainlensingestion:
    <<: *chainlensingestion-def
    depends_on:
      - rpcnode
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.55

  chainlensweb:
    <<: *chainlensweb-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.56

  chainlensnginx:
    <<: *chainlensnginx-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.57







  splunk:
    << : *splunk-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.42

  otelcollector:
    << : *otelcollector-def
    << : *docker-logging
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.43

  ethlogger:
    << : *ethlogger-def
    << : *docker-logging
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.44

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --docker_only=true
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.45



volumes:
  public-keys:
  prometheus:
  grafana:
  splunk:
  ethlogger:
  blockscoutpostgres:

networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
