version: '3'
services:
    learning-token-backend:
        image: learning-token-backend
        ports:
            - '3000:3000'
        container_name: learning-token-backend
        environment:
            - APP_URL=http://localhost:3000/api
            - APP_PORT=3000
            - APP_SECRET=3QANyH2zMoHrfxqfRWTLbPM
            - APP_EXPIRES=3600
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - DB_TYPE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=password
            - DB_NAME=learning-token
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_TTL=600
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/app # Mount the current directory to /app in the container
            - /app/node_modules # Keep node_modules separate

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=learning-token
        ports:
            - '5432:5432'

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
